### ISSUE TITLE
What's your recommendation to use it in classes with Static Functions?

### ISSUE THREAD

**Issue by nemoryoliver** [infinum/floggy#15]
Currently, I create a global variable like final loggy = Loggy<MyLoggy>('ControllersManager');

I hope you can add to the docs how to properly use it on static functions. Thank you

**Comment by lukaknezic** [comment]
Hey, sorry for late reply, but yes. In class with static functions I would recommend creating static variable where you initialise loggy (So using it whiteout mixin)

**Comment by nemoryoliver** [comment]
Thank you
