### ISSUE TITLE
error when used with Mockito's GenerateMocks()

### ISSUE THREAD

**Issue by gmcdowell** [infinum/floggy#18]
I have submitted an issue on the [mockito repo](https://github.com/dart-lang/mockito/issues/349#issue-824116308).

I am not 100% sure which party is best placed to provide guidance/resolve
Will counter link just so everyone is in the loop as it where ;)

Any thoughts apprecaited

**Comment by itsJoKr** [comment]
Looking at that issue on Mockito, it looks like it was indeed issue with Mockito. I guess we can close this, feel free to reopen if you disagree.
