### ISSUE TITLE
PrettyDeveloperPrint

### ISSUE THREAD

**Issue by Chaitanyabsprip** [infinum/floggy#30]
I can't find the extension or the implementation of this any where. I would like to know where I can find it, or even how I can implement it myself.

**Comment by lukaknezic** [comment]
Hi, since `PrettyDeveloperPrinter` is using flutter as dependency that printer is part of [flutter_loggy](https://pub.dev/packages/flutter_loggy) library. I can see now that documentation is missing that part, will add it to documentation as well.

**Comment by lukaknezic** [comment]
Improved documentation in #34
