### ISSUE TITLE
wrap width

### ISSUE THREAD

**Issue by Chaitanyabsprip** [infinum/floggy#33]
If I am trying to log large json responses, the output is truncated, probably because there is a character limit in the terminal. If loggy could provide the functionality to wrap the lines at a given character/wrap length that would help in logging large string's. could also probably implement a replace function or possibly a formatted json output.

**Comment by lukaknezic** [comment]
Hey @Chaitanyabsprip,
Can you provide some example where this fails? I was trying to do something like:
```dart
loggy.debug(() {
      return List.generate(100000, (index) => index).fold<String>('', (value, element) => value += '-') +
          'Really long string';
    });
```
And `Really long string` is still visible, and whole output is there (100,000 characters + `Really long string`)

And what terminal and loggy printer are you using? (I tired with PrettyPrinter and DefaultPrinter, both worked)

**Comment by Chaitanyabsprip** [comment]
I am generally using an android phone, I am using kitty terminal with fish shell and pretty printer. This limit of characters is much larger when running the application on a physical iOS device.

**Comment by lukaknezic** [comment]
Hey, I just tried this with android device, android simulator and iOS simulator but with zsh and everything works fine. I will try installing fish shell to see if it's up to that. 
You can also add your own printer that will parse the string before printing it if you want possibly quicker solution 😃

**Comment by Chaitanyabsprip** [comment]
so I'll first test this with zsh too, hopefully that works, if it still doesn't, I'll try to debug more and report whatever I find out, if anything at all.

**Comment by lukaknezic** [comment]
I didn't have any success in replicating this.

My suggestion if anyone has this issue is to make your own printer to solve this issue where you can easily then control how to print things 😃.

I'll close this issue now, but if you figure out why and fix the printer, PR's is welcome 🙂 
Closing #32 as well since those issues are connected.
