### ISSUE TITLE
[Bug] PrettyDeveloperPrinter not working

### ISSUE THREAD

**Issue by Chaitanyabsprip** [infinum/floggy#38]
OS: MacOS BigSur 11.5.2
Flutter app running on Kitty Terminal Emulator
testing on: iOS simulator iPhone 12 Pro Max

when I use PrettyDeveloperPrinter with iOS, nothing is being printed to console. 
I have come across something similar with `PrettyPrinter` with `showColors: true`. On iOS, the showColor option doesn't color the output, instead just prints the escape characters as is.

**Comment by strmchsr** [comment]
@Chaitanyabsprip any update regarding this, I am facing the similar issue
