### ISSUE TITLE
Not clear how filtering can be used

### ISSUE THREAD

**Issue by devanshu89w** [infinum/floggy#40]
Hi,

from the documentation it is not clear how to use flittering.

can you share a complete example of how to use it?

Thank you,
Devanshu

**Comment by itsJoKr** [comment]
Hey @devanshu89w 

So, one way I use it to exclude spammy logging that I don't need often, for example:

```
  Loggy.initLoggy(
    ... // other stuff
    filters: [
      BlacklistFilter([SocketLoggy])
    ],
  );
```
In the app I have ton of socket messages and I created SocketLoggy. So with this `BlacklistFilter` they are not logged as they would clog the console. If I'm interested in debugging socket then I'll remove this line. One possibility is to use `WhitelistFilter([SocketLoggy])` which will log only socket messages.

Another way I use it is that I redirect logs to Firebase Crashlytics events, like this:

```
  Loggy.initLoggy(
    logPrinter: (appBuildMode == AppBuildMode.release) ? const FirebaseLogPrinter() : PrettyDeveloperPrinter(),
    filters: [
      if (appBuildMode == AppBuildMode.release) 
        ReleaseLogFilter(),
    ],
  );
```

And in this case I extend filter and do some logic there to avoid logging all the data. When crash happens, the firebase would send all the events with crash and that can help me with debugging the crash.

Hope that answers your question. I'll add mark to this task to update the documentation.
