### ISSUE TITLE
The Windows Android Studio log print is incomplete

### ISSUE THREAD

**Issue by szxv587** [infinum/floggy#45]
The Windows Android Studio log print is incomplete

**Comment by lukaknezic** [comment]
Can you give me more information?
What are you using is it flutter/just dart?
What is incomplete? is printer not showing some stuff?

**Comment by szxv587** [comment]
Long JSON strings do not print completely

**Comment by paricleu** [comment]
I have also encountered this problem but it is not related to this plugin. See [here](https://github.com/flutter/flutter/issues/22665). 

TLDR: The full output is visible in the DevTools or you can use a workaround with debugPrint:
```
debugPrint(someSuperLongString, wrapWidth: 1024);
```

**Comment by lukaknezic** [comment]
Since this is not plugin issue I'm closing it.

You can also make your own printers that use `debugPrint` with wrapWidth if needed
