### ISSUE TITLE
FR: ringbuffer of log messages and push to server

### ISSUE THREAD

**Issue by haraldkofler** [infinum/floggy#46]
For debugging app's in the wild, it would be convenient to log floggy alls logs into a ring-buffer and have a feature to upload a zipped archive of these buffered lined onto a server.

Is such a behavior maybe already implemented? Or is there another best practice to get the logs of remote devices?

**Comment by itsJoKr** [comment]
Hey @haraldkofler 

I use Firebase Crashlytics and logs for similar thing, but obviously you could in similar way use any other service to upload logs to.

The way I accomplish this is through use of different printer: https://github.com/infinum/flutter-bits/blob/master/loggy_crashlytics/firebase_log_printer.dart

And in loggy init I have something like:

```dart
  Loggy.initLoggy(
    logPrinter: (kReleaseMode) ? const FirebaseLogPrinter() : PrettyDeveloperPrinter(),
    blacklist: [
      if (kReleaseMode) DioLoggy,
    ],
```

**Comment by itsJoKr** [comment]
I'll close this issue, if there's any more question feel free to ask.
