### ISSUE TITLE
[pretty_loggy_dio] Can't pretty log Json/Map and almost every request runs into the print character limit

### ISSUE THREAD

**Issue by paricleu** [infinum/floggy#47]
While using the LoggyDioInterceptor I noticed that my requests always triggered the try/catch block [here](https://github.com/infinum/floggy/blob/f7f9d2c31f30e71afb3550dbeb81e9688bc33df9/flutter_loggy_dio/lib/flutter_loggy_dio/dio_logger.dart#L126).
The exception thrown is FormatException because
```
data.toString()
```
returns the Json without quotes which can't be parsed by
```
JsonDecoder().convert(...)
```

I'd suggest using the [pretty_dio_logger](https://github.com/Milad-Akarie/pretty_dio_logger/blob/master/lib/pretty_dio_logger.dart) approach to log as json/Map. The only major difference with pretty_dio_logger is it logs the response line by line instead of using line breaks as this plugin.
In my opinion using line breaks is superior because the calls can't be broken up by simultaneous logging calls. 
However it leads to irritation because long calls (a small json is enough) are being cut of on Android when using the `print` method(like the DefaultPrinter()) instead of `debugPrint`(with maxWidth) or `developer.log`. I'd suggest adding some Info to the readme to stop confusion and issues like #45.

I'll see if I have the time to fix the json issue in the future and mainly opened this issue to get feedback on the linebreak vs print by line approach. What do you think?

**Comment by lukaknezic** [comment]
@paricleu Since you are already working on this, is it okay if I assign you to this bug? 😃

**Comment by zenled** [comment]
Closing, the latest release of the [flutter_loggy_dio](https://pub.dev/packages/flutter_loggy_dio) package should resolve this.
If the problem persists, feel free to reopen this issue.
