### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by whes1015** [infinum/floggy#52]
How can i modify LoggyStreamWidget() Page's "EXPAND" and "COLLAPSE"?

**Comment by lukaknezic** [comment]
Hey,

The widget is currently using `collapsedIconTapHint` and `expandedIconTapHint` from `MaterialLocalizations`.
Not sure if you can really modify it. I think easiest way would be to create custom widget for now.

I'll add more customisation to `StreamWidget` so this will be possible in future versions.
