### ISSUE TITLE
Can this be used outside of a class?

### ISSUE THREAD

**Issue by ZaLiTHkA** [infinum/floggy#53]
I'm building a CLI tool at the moment, and I have some helper functions in separate files, not contained inside classes themselves...

I've got this working perfectly in my main application logic, but I'm battling to use it inside standalone functions. any suggestions here?

---

_edit:_ just to clarify, I'm able to use `log` (and it's level-specifc variants) after callling `Loggy.initLoggy()` inside my individual functions.. but is the idea that each of these helper functions needs it's own logger then?

_or_ should I perhaps create one helper function to wrap this initialisation, and then just call that from my other functions..? hmmm.. sorry for the potentially stupid questions, big time Dart newbie over here.. 👋🏼

**Comment by lukaknezic** [comment]
Hey @ZaLiTHkA, I think you want to use `GlobalLoggy`. So in helper functions you can call `logDebug` and `GlobalLoggy` will print them. Or you can make your own global `HelperLoggy` you can use.

Let me know if this is what you were looking 🙂

**Comment by ZaLiTHkA** [comment]
I think I just worked that out now... it seems I am just using the `GlobalLoggy` instance everywhere already anyway. at least, that's what the terminal feedback shows..

just for clarification, should I only call `Loggy.initLoggy()` **once** when my app starts? or should I do that at the top of each class in my app?

**Comment by lukaknezic** [comment]
You have to call that just on start. 

If you want to use custom Loggy instead of Global one then you have to add it as mixin to the class (ex. `class MyClass mixin UiLoggy{`. Then instead of `logDebug` use `log.debug`. You can get more info from logs that way.

**Comment by ZaLiTHkA** [comment]
sorted, thanks for the help. and the super quick responses.. 🖖🏼 

I'm gonna go make some pretty logs now. (:
