### ISSUE TITLE
[loggy] Custom log level example

### ISSUE THREAD

**Issue by zenled** [infinum/floggy#6]
I have a question regarding the documentation example for [Custom log levels and expanding existing printers](https://github.com/infinum/floggy/tree/master/loggy#custom-log-levels-and-expanding-existing-printers).

Documentation Example:
```dart
extension SocketLevel on LogLevel {
  // LogLevel is just a class with `name` and `priority`. Priority can go from 1 - 99 inclusive.
  static const LogLevel socket = LogLevel('socket', 32);
}
```

What is the purpose of making an `extension`? 
Someone less familiar with Dart might think that he can get the `socket` by calling `LogLevel.socket`, when in fact this won't work.

**Comment by lukaknezic** [comment]
Okay this maybe needs better documentation in that case. Extending `LogLevel` is just to add more levels if you need more grainularity for logging.
Currently warning level has priority of '8', adding new level with priority of '9' will mean that new level has more priority and it will be shown if you specified that only 'warning' and above logs should be shown.

In the readme I also added in line below that (LogLevel extension), that when adding levels you should also extend loggy like so:
```dart
extension SocketLoggy on Loggy {
  void socket(dynamic message, [Object error, StackTrace stackTrace]) => log(SocketLevel.socket, message, error, stackTrace);
}
```
And that will make it possible to call your logger. (Note this will make socket available for every logger not just custom ones, so even included UiLoggy and NetworkLoggy can call it):
```dart
class MyClass with UiLoggy{
  void main(){
    loggy.socket('my logger message with socket level');
  }
}
```

**Comment by zenled** [comment]
Ok, 
It doesn't matter how you create a new LogLevel, the important part is to add an extension to `Loggy`.

You decided to create a new LogLevel like this:
```dart
// Example 1
extension SocketLevel on LogLevel {
  static const LogLevel socket = LogLevel('socket', 32);
}
```

But it could also be created like this (as a global variable):
```dart
// Example 2
const LogLevel socketLogLevel = LogLevel('socket', 32);
```

or like this:
```dart
// Example 3
class SocketLevel {
    static const LogLevel socket = LogLevel('socket', 32);
}
```

My question is, why did you choose the approach in `Example 1`, and not the approach in `Example 2` or `Example 3`?

**Comment by lukaknezic** [comment]
Oh okay, i misinterpreted the question then. Yeah you make a valid point, for example maybe your `Example 2` might be better since it's one liner.
Now that I think about it there is no reason for extension. I will update example and readme with your `Example 2`.
