### ISSUE TITLE
Not pretty priting if using dio to decode

### ISSUE THREAD

**Issue by itsJoKr** [infinum/floggy#65]
When using

```dart
    final response = await _dio.get<List<dynamic>>(
      ApiEndpoints.tournaments,
    );
```

it would not print nice but all will be printed in one line.

Reason:
In the case dio is decoding json, the dio_logger will get string like `[{id: 1}, {id: 2}]`. Note the missing `""` from json. And it would crash with FormatException on line 129 and go in catch clause:

```dart
    try {
      final Object object = const JsonDecoder().convert(data.toString());
      const JsonEncoder json = JsonEncoder.withIndent('  ');
      value = '║  ${json.convert(object).replaceAll('\n', '\n║  ')}';
    } catch (e) {
      value = '║  ${data.toString().replaceAll('\n', '\n║  ')}';
    }
```

Workaround is to always get the string and decode it by yourself:

```dart
    final response = await _dio.get<String>(
      ApiEndpoints.tournaments,
    );
```

**Comment by lucavenir** [comment]
> Workaround is to always get the string and decode it by yourself

Which defies the purpose of using `dio` in the first place, just to address this issue.
Is there any chance this can be addressed or is there any other workaround?

**Comment by zenled** [comment]
Closing, this has been improved in the late release of the [flutter_loggy_dio](https://pub.dev/packages/flutter_loggy_dio) package.
