### ISSUE TITLE
[flutter_loggy_dio] LoggyDioInterceptor default LogLevel

### ISSUE THREAD

**Issue by zenled** [infinum/floggy#7]
The `LogLevel-s` in `LoggyDioInterceptor` might be confusing.

The logging in `onRequest` (`requestHeader`, `requestBody`) has a `LogLevel.debug`.
The logging in `onResponse` (`responseHeader`, `responseBody`) has a `LogLevel.info`.

Is there a reason for having different LogLevels between request and response?
Ideally, I would like this to be customizable.

**Comment by itsJoKr** [comment]
We should add 2 log levels (request and response) with better emojis.

**Comment by zenled** [comment]
I wouldn't add new LogLevels, I'm not sure if it makes sense to have a `LogLevel.request` and `LogLevel.response`.

I would allow the user to specify the LogLevel, for both the `request` and the `response`, and also for `error`.
For `request` and `response`, I would make the default to be `LogLeve.info`.
