### ISSUE TITLE
Release 2.0.3 for Flutter 3.22

### ISSUE THREAD

**Issue by jpohhhh** [infinum/floggy#77]
Depending on flutter_loggy with Flutter 3.22 leads to build errors. TL;DR: deprecated TextTheme getters

It looks like these references are fixed at top of tree, and pushing an update to pub.dev for 2.0.3 would be sufficient to resolve the issue.

Error logs:
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006021-000C19E20147401E, name:My Mac }
{ platform:macOS, arch:x86_64, id:00006021-000C19E20147401E, name:My Mac }
../../.pub-cache/hosted/pub.dev/flutter_loggy-2.0.2/lib/flutter_loggy/ui/widgets/loggy_stream_item_widget.dart:86:52: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
                style: Theme.of(context).textTheme.headline6!.copyWith(
                                                   ^^^^^^^^^
../../.pub-cache/hosted/pub.dev/flutter_loggy-2.0.2/lib/flutter_loggy/ui/widgets/loggy_stream_item_widget.dart:95:52: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
                style: Theme.of(context).textTheme.subtitle1!.copyWith(
                                                   ^^^^^^^^^
../../.pub-cache/hosted/pub.dev/flutter_loggy-2.0.2/lib/flutter_loggy/ui/widgets/loggy_stream_item_widget.dart:125:48: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText2'.
            style: Theme.of(context).textTheme.bodyText2!.copyWith(
                                               ^^^^^^^^^
../../.pub-cache/hosted/pub.dev/flutter_loggy-2.0.2/lib/flutter_loggy/ui/widgets/loggy_stream_item_widget.dart:138:48: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText2'.
            style: Theme.of(context).textTheme.bodyText2!.copyWith(
                                               ^^^^^^^^^
../../.pub-cache/hosted/pub.dev/flutter_loggy-2.0.2/lib/flutter_loggy/ui/widgets/loggy_stream_widget.dart:88:54: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText2'.
                  style: Theme.of(context).textTheme.bodyText2!.copyWith(
                                                     ^^^^^^^^^
../../.pub-cache/hosted/pub.dev/flutter_loggy-2.0.2/lib/flutter_loggy/ui/widgets/loggy_stream_widget.dart:97:52: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText2'.
                style: Theme.of(context).textTheme.bodyText2!.copyWith(
                                                   ^^^^^^^^^
../../.pub-cache/hosted/pub.dev/flutter_loggy-2.0.2/lib/flutter_loggy/ui/widgets/loggy_stream_widget.dart:108:48: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText2'.
            style: Theme.of(context).textTheme.bodyText2!.copyWith(
                                               ^^^^^^^^^
Target kernel_snapshot failed: Exception

**Comment by jpohhhh** [comment]
n.b. replacing your flutter_loggy dependency with this works around the issue for now:

  flutter_loggy:
    git:
      url: https://github.com/infinum/floggy.git
      path: flutter_loggy

**Comment by itsJoKr** [comment]
@lukaknezic Can you release new version of flutter_loggy?

All of this is fixed by @zenled before 3 months, but you guys only released the flutter_loggy_dio. You need to release flutter_loggy too on pub.dev.

**Comment by lukaknezic** [comment]
New release 2.0.3 is now on pub.dev
